# fly.toml app configuration file generated for bunime on 2024-12-08T01:20:15-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bunime'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
